add lint and test targets to all linux Docker images
jenkinsci/jnlp-agents pull request #22
Opened 2021-01-18 16:23 UTC by MarckK

2021-01-19 15:32 UTC, slide requested changes

2021-01-19 15:32 UTC, slide commented on Jenkinsfile
> +        stage('Build and Test') {
I think we would only need to lint when `infra.isTrusted()` is false, e.g., for builds on ci.jenkins.io for PR's and so forth. The builds on trusted only occur on the master branch and we don't merge directly to master.

2021-01-19 15:57 UTC, dduportal commented on Jenkinsfile
> +        stage('Build and Test') {
The idea that is tested in this draft PR would be to use the tar export of the image , after the tests. This should be then stashed, and unstashed by the untrusted infra for the "push only".

OR we can keep the current behavior that rebuild the image on the trusted infra, without the lint and tests steps. but it feels weird.

2021-01-19 16:25 UTC, dduportal commented on Jenkinsfile
> +        stage('Build and Test') {
Hello @slide ! We are not sure to understand how it works:

- For the trusted infra, what are the expected steps to be run? Push only (so the tested image should be unstashed) or build and push (and rebuild the image a 2nd time)?
- Is there a reason to not use 2 separated pipelines for both instances? (or a the Jenkinfile for untrusted, and a pipeline library for better control on the untrusted infra)

2021-01-20 18:14 UTC, dduportal commented on Jenkinsfile
> +        stage('Build and Test') {
Feedback applied 👍

2021-01-20 20:36 UTC, slide approved these changes

2021-01-20 20:36 UTC, merged